version: 2.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout

      - restore_cache:
          key: hotel-booking-{{ checksum "pom.xml" }}

      - run:
          name: Go Offline
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: hotel-booking-{{ checksum "pom.xml" }}

      - run:
          name: Unit Tests
          command: mvn test

  build:
    docker:
      - image: circleci/buildpack-deps:stretch
        
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build . -t hindsightsoftware/hotel-booking

workflows:
  build_and_test:
    jobs:
      - build
