version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout

      - restore_cache:
          key: hotel-booking-{{ checksum "pom.xml" }}

      - run:
          name: Go Offline
          command: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: hotel-booking-{{ checksum "pom.xml" }}

      - run:
          name: Unit Tests
          command: mvn test

  build:
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: |
            docker build . -t hindsightsoftware/hotel-booking:latest

      - run:
          name: Save image to an archive
          command: |
            mkdir /tmp/image
            docker save -o /tmp/image/hotel-booking.tar hindsightsoftware/hotel-booking:latest

      - persist_to_workspace:
          root: ~/repo
          paths:
            - /tmp/image

  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - checkout

      - setup_remote_docker

      - attach_workspace:
          at: /tmp

      - run:
          name: Load image
          command: |
            docker load --input /tmp/image/hotel-booking.tar

      - run:
          name: Publish
          command: |
            docker login --username=$DOCKER_USER --password=$DOCKER_PASS
            docker push hindsightsoftware/hotel-booking:latest

            docker tag hindsightsoftware/hotel-booking:latest hindsightsoftware/hotel-booking:$(git describe --always)
            docker push hindsightsoftware/hotel-booking:$(git describe --always)

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
